### PR TITLE
Update Tutorial for 2020 VA Course

### PR DESCRIPTION
**Pull request by keckelt**
# Switch to Jupyterlab

The changes necessary to setup a running JupyterLab environment are listed below.
In addition, I've updated the README and Getting Started files a bit

## Setup 
1. Adding ipywidgets and nodejs (to install the JupyterLab extension, see below) to requirements.txt
2. IPyWidgets need an extension for Jupyterlab: https://ipywidgets.readthedocs.io/en/latest/user_install.html
A postBuild file was added to setup a custom Binder enrionment with the extension.
I've added `--minimize=False` as described here: https://github.com/binder-examples/jupyter-extension/commit/adbab4791737dd3ff8b29cdb4dc2b76042d301b9 as it helped against failing builds

Test URL: https://mybinder.org/v2/gh/JKU-ICG/python-visualization-tutorial/juypterlab_widgets?urlpath=lab

# Split Static and Interactive Plotting

* I've moved the ipywidgets discussion to the Altair notebook
* The Altair notebook is now called InteractivePlotting
* Consequently, the Plotting notebook is now called StaticPlotting

# Remove Plotly

Plotly is great, but discussing it in addition to the other libraries goes beyond the time available.
I've therefore removed the notebook that would have needed a major overhaul anyway.

The machine learning notebook is therefore #5 again.

# Misc

* All notebooks were executed.
* I've updated the links to the next notebook that are at the bottom of each notebook.

### CODE REVIEW

**Comment by keckelt** [comment]
The linked example is garbage, simply adding nodejs and ipywidgets to requirements.txt and adding the labextension in the postBuild steps works though.

I.e. as described here: https://ipywidgets.readthedocs.io/en/latest/user_install.html

**Comment by keckelt** [comment]
Added minimize true as descirbed here: https://github.com/binder-examples/jupyter-extension/commit/adbab4791737dd3ff8b29cdb4dc2b76042d301b9
as it helped against failing builds

**Review by PatrickAdelberger — APPROVED** [review]
okay :+1:

**Comment by keckelt** [comment]
I've reused the temp measurement example for One Hot encoding using pandas so the two examples match.

**Pull request merged**
